### ISSUE TITLE
When next version(3.4.7?) will be shipped?

### ISSUE THREAD

**Issue by ynojima** [ruby-gettext/gettext#104]
First of all thanks for your awesome work!

When is the ETA of the next version? 

I want to use this fix(https://github.com/ruby-gettext/gettext/commit/a318f8fdac592673de58aa26672541b44e773a94) in my application.

Thanks!

**Comment by kou** [comment]
Done!

**Comment by ynojima** [comment]
Thank you for prompt response! I really appriciate it.
