### ISSUE TITLE
Generating PO/MO Files

### ISSUE THREAD

**Issue by ziyan-junaideen** [ruby-gettext/gettext#34]
I started a new Sinatra project that was based on a old Sinatra template which used Gettext for translation. There we had a `Rake` task to generate `PO` files and convert to `MO` and then use it.

I am very new to translation and might be missing out some thing. But what I think is when the versions change so did the structure of the lib.

How can I write a rake task that will generate the PO/MO files.

This is the rake task I am using and it gives and error:

```
require 'gettext'
require 'gettext/tools'

namespace :gettext do 

  desc "Update pot/po file"
  task :update_po do 

    location = File.expand_path('../../src/', File.dirname(__FILE__))

    files = nil
    Dir.chdir( location ) do 
      files = Dir.glob("{lib,helpers,views,routes}/**/*.{rb,rhtml,erb,slim}")
      files.concat( Dir.glob( "*.rb" ) )

      puts "Files selected are: "
      p files

      GetText.update_pofiles($project, files, "#{$project} #{$version}", po_root: 'i18n')
    end

  end

  desc "Make mo files from PO"
  task :make_mo do

  end

end
```

When running, I am getting this: `NoMethodError: undefined method`update_pofiles' for GetText:Module`

Help is greatly appreciated.

**Comment by kou** [comment]
I've released gettext-slim gem.
