### ISSUE TITLE
Question about usage of .edit.po and rate task ordering

### ISSUE THREAD

**Issue by domcleal** [ruby-gettext/gettext#36]
Hey,

I'm trying to work out how to make best use of the .edit.po files that started being generated in 3.1.13, and would appreciate some guidance or an example project that's making use of them.

I'd first like to clarify exactly what they're for: is the idea that gettext generates the .edit.po for external editing and syncing of translations, and then merges that into the .po which is the file actually used?  Would you keep .edit.po outside of version control?

[Our project](https://github.com/theforeman/foreman) uses gettext_i18n_rails which defines gettext:find and setup via GetText::Tools::Task.define.  We import updates to .po files from the Transifex web site with "tx pull -f", which can be configured to update `locale/<lang>/foreman.po` etc.

Now, I could run gettext:find (aka gettext:po:update) to generate .po and .edit.po files, then tx pull to sync translations to the .edit.po files, then run gettext:find again to re-sync .edit.po to .po.  This appears to work, though it is incredibly slow.

Or should I perhaps download .po files from Transifex to .edit.po, then run gettext:find which merges them into .po?

Thanks for any thoughts on the subject.

**Comment by kou** [comment]
> would appreciate some guidance or an example project that's making use of them.

Here is a project that uses the .edit.po mechanism: https://github.com/ruby-gettext/jekyll-task-i18n
You can find a small guidance in README of the project.

http://droonga.org/ uses the project. http://droonga.org/community/contribution/i18n/ may also help you.

> is the idea that gettext generates the .edit.po for external editing and syncing of translations, and then merges that into the .po which is the file actually used?

Yes. You're right.

> Would you keep .edit.po outside of version control?

Yes. .edit.po should not be added into version control system.

> Now, I could run gettext:find (aka gettext:po:update) to generate .po and .edit.po files, then tx pull to sync translations to the .edit.po files, then run gettext:find again to re-sync .edit.po to .po. This appears to work, though it is incredibly slow.

Umm... Could you show command lines to reproduce the situation on my environment? I want to confirm it on my environment.

> Or should I perhaps download .po files from Transifex to .edit.po, then run gettext:find which merges them into .po?

Sorry. I couldn't find the different between the alternative way and the current way...

**Comment by domcleal** [comment]
> http://droonga.org/ uses the project. http://droonga.org/community/contribution/i18n/ may also help you.

Thanks, that was useful to see it in action.

> > Now, I could run gettext:find (aka gettext:po:update) to generate .po and .edit.po files, then tx pull to sync translations to the .edit.po files, then run gettext:find again to re-sync .edit.po to .po. This appears to work, though it is incredibly slow.
> 
> Umm... Could you show command lines to reproduce the situation on my environment? I want to confirm it on my environment.

Sure:

    git clone https://github.com/theforeman/foreman
    cp config/database.yml{.example,}
    cp config/settings.yaml{.example,}
    bundle install
    bundle exec rake db:migrate && rake db:seed
    time bundle exec rake gettext:find

If you compare develop (gettext 3.1.13) to the 1.7-stable branch, which used gettext ~> 2.0 (delete Gemfile.lock, bundle install) then you'll probably see timings for gettext:find like this:

    real    5m24.546s (on develop)
    real    0m38.497s (on 1.7-stable)

I've not dug into the causes of that yet, thanks for checking.

> > Or should I perhaps download .po files from Transifex to .edit.po, then run gettext:find which merges them into .po?
> 
> Sorry. I couldn't find the different between the alternative way and the current way...

Sorry, I didn't explain that clearly.  It occurred to me that I don't really need the .edit.po files to exist before downloading the latest translations from Transifex, so could:

1. Download .po files from Transifex, create and store at locale/*/foreman.edit.po
1. Run rake to extract new strings, and merge the existing .edit.po files into .po
1. Commit updated .pot and .po files

I don't think I need to run the rake tasks before downloading current translations.

**Comment by domcleal** [comment]
> If you compare develop (gettext 3.1.4) to the 1.7-stable branch, which used gettext ~> 2.0 (delete Gemfile.lock, bundle install) then you'll probably see timings for gettext:find like this:
> 
> real    5m24.546s (on develop)
> real    0m38.497s (on 1.7-stable)
> 
> I've not dug into the causes of that yet, thanks for checking.

One more data point: gettext 3.1.2 is 13m12.854s, so it looks like 3.1.4 is actually a large improvement.  Perhaps the time_stamp feature?

**Comment by kou** [comment]
Thanks for showing command line. I can confirm it.

Bottle neck is the process to find fuzzy entries process on merging .edit.po with .pot. The process was improved at gettext 3.0.9. But it's still slow. The current algorithm is O(nm). (n = The number of msgid in .pot, m = The number of msgid in .edit.po) 

Ref.:
  * For n: https://github.com/ruby-gettext/gettext/blob/master/lib/gettext/tools/msgmerge.rb#L96
  * For m: https://github.com/ruby-gettext/gettext/blob/master/lib/gettext/tools/msgmerge.rb#L226


I think that we can improve performance by using [SimString](http://chokkan.org/software/simstring/). It is implemented in C++ and provides SWIG based Ruby bindings.

If it's implemented by pure Ruby (and `Hash` is used as storage instead of file based storage), gettext can use it to improve speed...

**Comment by kou** [comment]
Could you try gettext 3.1.5? It improves fuzzy matching performance a bit.

**Comment by domcleal** [comment]
That's helped a lot, thanks @kou!

    real    3m15.798s

I'll close this as you've answered my question, and improved it greatly.  Cheers.

**Comment by kou** [comment]
Thanks for confirming it!
