### ISSUE TITLE
gettext can't handle HAML files properly

### ISSUE THREAD

**Issue by psy-q** [ruby-gettext/gettext#4]
We're running into a lot of headaches trying to parse HAML files, most of them can be traced back to the rake gettext:find task using ruby_parser somewhere, and using Ruby 1.9.

If gettext could be rewritten to use ripper instead of ruby_parser when running on Ruby 1.9, this might fix things?

See here:

http://rails-bestpractices.com/blog/posts/22-use-ripper-instead-of-ruby_parser

Problems are all over the place, and even when we remove all Ruby 1.9 syntax from a file, gettext and ruby_parser still fail. For example this file, it makes rake gettext:find crash:

https://github.com/zhdk/madek/blob/master/app/assets/javascripts/tmpl/media_resource/thumb_box/actions/menu.tmpl.haml

With the following error:

Can't change the value of true

And this error comes from ruby_parser, but could be prevented if gettext used a different parser.

I've reported a similar ticket at ruby_parser anyhow, to see if the problem might be there:

https://github.com/seattlerb/ruby_parser/issues/43

**Comment by kou** [comment]
I'll release gettext-haml gem soon: https://github.com/ruby-gettext/gettext-haml
