### ISSUE TITLE
gettext:find does not find interpolated strings in .rb files

### ISSUE THREAD

**Issue by ceres629** [ruby-gettext/gettext#42]
It was indicated here: https://github.com/grosser/gettext_i18n_rails/issues/146 that i should raise this issue with the gettext gem:

Running gettext:find doesn't seem to find interpolated strings in .rb files.

```
#In a .rb file
test = _("Test: this key is found by gettext")
test2 = "#{_("Test: this key is not found by gettext")}"
```

In .haml files however, the above examples both work fine and gettext:find correctly identifies both as being strings to be translated.

**Comment by kou** [comment]
Thanks for your report.
We should reimplement Ruby parser to support the case. We're using irb based parser but we should use Ripper for it.

**Comment by kou** [comment]
3.3.0 has Ripper based parser. It fixed this.
