### ISSUE TITLE
Plural context with zero

### ISSUE THREAD

**Issue by mysmallidea** [ruby-gettext/gettext#46]
It would be great if there were a way to specify a special [plural form](https://github.com/ruby-gettext/gettext/blob/master/lib/gettext.rb#L155) when the count is zero. Here's an example of my translation using i18n: 

      login_count:
        one: Logged in once
        other: Logged in %{count} times
        zero: Never logged in

**Comment by kou** [comment]
Thanks for your suggestion but it's out of scope of gettext.
