### ISSUE TITLE
false positive on string to translate?

### ISSUE THREAD

**Issue by MosesMendoza** [ruby-gettext/gettext#49]
When generating a `pot` file with ruby-gettext for the [puppet project](https://github.com/puppetlabs/puppet), we found some strings were identified for externalization which surprised us.

The code in question is a series of method definitions, here: https://github.com/puppetlabs/puppet/blob/master/lib/puppet/pops/types/type_formatter.rb#L115-L137.

An example is:
```ruby
  # @api private
  def string_PAnyType(_)     ; @bld << 'Any'     ; end
```

For some reason, when parsed by ruby-gettext, this method and others like it result in entries in our pot file:

```
#. @api private
msgid "Any"
msgstr ""
```

This full generated pot file is in https://github.com/puppetlabs/puppet/pull/5366.

Naively, it appears this combination of parenthesis and underscores in our method names is tripping up the parser? Or are we doing something incorrect here?

Our invocation is:
```
rxgettext -o locales/puppet.pot --no-wrap \
--sort-by-file \
--no-location \
--add-comments \
--msgid-bugs-address 'https://tickets.puppetlabs.com' \
--package-name 'Puppet automation framework' \
--package-version '4.8.1-116-g6dfd145 \
' --copyright-holder='Puppet, Inc.' \
--copyright-year=2016 <list of files...>
```

**Comment by kou** [comment]
3.3.0 has Ripper based parser and this is fixed.
