### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by AlexWayfer** [ruby-gettext/gettext#54]
Hello!

I found the [tutorial](http://www.yotabanana.com/hiki/ruby-gettext-howto.html) link in `README` that doesn't work.

Do you have a working tutorial?

**Comment by kou** [comment]
Unfortunately, no...

**Comment by AlexWayfer** [comment]
@kou I see [`TODO`](https://github.com/ruby-gettext/gettext/blame/a58c635/lib/gettext/tools/task.rb#L208) that is already 4 years old. Is this gem no longer supported?

I liked the `gettext` format, but it's very hard to setup this in Ruby project: what about `Rack` (I found `Locale::Middleware`), what about generation of files (`Rake` obscure tasks) and connecting into project…

**Comment by kou** [comment]
> Is this gem no longer supported?

Why? I've released a new version yesterday.
