### ISSUE TITLE
Fix the ruby-parser: `NoMethodError: undefined method `<<' for nil:NilClass`

### ISSUE THREAD

**Issue by ellcs** [ruby-gettext/gettext#68]
Hello again! :)

I receive following Error `NoMethodError: undefined method '<<' for nil:NilClass` within the glade parser:

```ruby
NoMethodError: undefined method `<<' for nil:NilClass
/home/mantel/repos/gettext/lib/gettext/tools/parser/ruby.rb:148:in `process_on_tstring_content'
/home/mantel/repos/gettext/lib/gettext/tools/parser/ruby.rb:234:in `block in on_default'
/home/mantel/repos/gettext/lib/gettext/tools/parser/ruby.rb:249:in `trace'
/home/mantel/repos/gettext/lib/gettext/tools/parser/ruby.rb:231:in `on_default'
```

This is the following line:

https://github.com/ruby-gettext/gettext/blob/4e7702d83dc9711b5a17a4cf1e7a5d7ef1b3a703/lib/gettext/tools/parser/ruby.rb#L148

Here are some investigation notes:
- `@string_stack.last` is `nil`
- `token` is the content of a shell-call: `echo hi`

I will add a regression test.

**Comment by kou** [comment]
Thanks.
This will be fixed by #67.
