### ISSUE TITLE
Using %I[] causes NoMethodError: undefined method `<<' for nil:NilClass

### ISSUE THREAD

**Issue by kramuenke** [ruby-gettext/gettext#71]
on gettext 3.3.2 when using ruby's %I we got the following error on parsing source files:

```
NoMethodError: undefined method `<<' for nil:NilClass
``` 

Since the actual list of symbols did not require interpolation we changed it to %i to avoid parsing errors with gettext

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
