### ISSUE TITLE
Ignored Gettext syntax when <%- is used in ERB files

### ISSUE THREAD

**Issue by MichaelHoste** [ruby-gettext/gettext#75]
It seems that there is a parsing issue when `<%-` is used in an ERB file.

In this example, "Hello" is not added to the PO(T) file:

```erb
<%- content_for :title, "Title" %>

<%= _("Hello") %>
```

I don't exactly know why, but using:

```erb
<%= content_for :title, "Title" %>

<%= _("Hello") %>
```

or something like:

```erb
<%- "Title" %>

<%= _("Hello") %>
``` 

solves this issue.

Do you have any idea why this happens?

**Comment by MichaelHoste** [comment]
@kou it seems that fixing #77 you also solved this issue!
Using the master branch, I was able to make it work on my failing examples.

Thank you, again!

**Comment by kou** [comment]
Good news!

(Sorry. I'm busy recently. I didn't check this yet.)
