### ISSUE TITLE
msgmerge is very verbose

### ISSUE THREAD

**Issue by akimd** [ruby-gettext/gettext#81]
Hi,
msgcat supports --no-report-warning, but msgmerge does not.  And msgmerge is very verbose about fuzzy message.  Could it also have support for it?
Cheers!

**Comment by kou** [comment]
Could you provide `.po`/`.pot` files that reproduce this?

**Comment by kou** [comment]
Done.

**Comment by akimd** [comment]
Hi!
Well, you've been very fast, thanks a lot!  Do you still need example files?

**Comment by kou** [comment]
No. Please provide them if you find any problem of the feature.

**Comment by akimd** [comment]
I confirm it fixed my problem.  Many thanks!

**Comment by kou** [comment]
Good to know!
