### ISSUE TITLE
is Rails 6 supported?

### ISSUE THREAD

**Issue by mathieujobin** [ruby-gettext/gettext#82]
Has anyone been able to use this with Rails 6? 

I used this gem back in the days with Rails 1.
When I upgraded to Rails 4, I switch to FastGettext which now seems unmaintained and broken.

anyone else in a similar situation?

Or should I just convert my po files to rails yaml?

**Comment by MichaelHoste** [comment]
We use this as a dependency of [translation/rails](https://github.com/translation/rails) and it works great with Rails 6.

It seems that FastGettext uses a very old bundled version of this gem (https://github.com/grosser/fast_gettext/tree/master/lib/fast_gettext/vendor), and that could be your issue.

**Comment by mathieujobin** [comment]
Indeed, I should standardize back into using this gem instead.
Thank you
