### ISSUE TITLE
Nn_() not recognised

### ISSUE THREAD

**Issue by kramuenke** [ruby-gettext/gettext#86]
Hi gettext team,

we are observing the parser in 3.3.7 not picking up `Nn_()` expression and dropping them from our `.pot` files. Any help would be appreciated.

Example: `Nn_('T-Shirt', 'T-Shirts')`

Our current version is 3.2.9

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.

**Comment by kramuenke** [comment]
We can see `Nn()` coming through again Thank you!

Can you release a new patch version?

**Comment by kou** [comment]
We'll release a new version once #85 is solved.
