### ISSUE TITLE
Locale fallback if missing translation (ex: `en_US` => `en`)

### ISSUE THREAD

**Issue by MichaelHoste** [ruby-gettext/gettext#89]
I was wondering if GetText has already some existing mechanism to deal with locale fallbacks.

It would be really useful for regional languages (like `en_US`) so we could avoid duplicating, and co-evolving, most translations that are the same.

In a project where `fr` is the source language and `en` and `en_US` are the target languages, it would be nice if a missing translation to `en_US` would fallback to `en` **before** fallbacking to `fr` (current behaviour).

I did a quick ugly hack in `text_domain.rb` (`translate_singular_message`) and it seems to work well for me:

I replaced 

```ruby
return mo[msgid] if mo.has_key?(msgid)
```

by 

```ruby
if mo.has_key?(msgid)
  return mo[msgid]
elsif lang.to_s.include?('_')
  new_lang = Locale::Tag.parse(lang.to_s.split('_').first) #  yes, ugly for now...
  return translate_singular_message(new_lang, msgid)
end
```

If I implement this solution correctly, would you consider merging it @kou ? Or are there any existing alternative?

**Comment by kou** [comment]
> If I implement this solution correctly, would you consider merging it?

Sure.

I think that we should do this in `TextDomainManager` not `TextDomain`.

I haven't tried it but this may work:

```diff
diff --git a/lib/gettext/text_domain_manager.rb b/lib/gettext/text_domain_manager.rb
index e329fb4..c4ced0c 100644
--- a/lib/gettext/text_domain_manager.rb
+++ b/lib/gettext/text_domain_manager.rb
@@ -77,11 +77,12 @@ module GetText
     end
 
     def each_text_domains(klass) #:nodoc:
-      lang = Locale.candidates[0]
-      ClassInfo.related_classes(klass, @@gettext_classes).each do |target|
-        if group = @@text_domain_group_pool[target]
-          group.text_domains.each do |text_domain|
-            yield text_domain, lang
+      Locale.candidates.each do |lang|
+        ClassInfo.related_classes(klass, @@gettext_classes).each do |target|
+          if group = @@text_domain_group_pool[target]
+            group.text_domains.each do |text_domain|
+              yield text_domain, lang
+            end
           end
         end
       end
```

**Comment by MichaelHoste** [comment]
Thanks a lot for your suggestion @kou !

I'll create a new PR for this in the following weeks with some tests.

**Comment by MichaelHoste** [comment]
I finally created the PR here: #90 

The suggested implementation worked great!

**Comment by MichaelHoste** [comment]
The PR was merged and released, I guess we can close this issue now.
